version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions-patch-and-minor:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/web-app"
    schedule:
      interval: "weekly"
    groups:
      web-app-patch-and-minor:
        update-types:
          - "minor"
          - "patch"

