name: Dependency Review

on:
  pull_request:
    paths:
      - ".github/workflows/**"
      - ".github/dependabot.yml"
      - "web-app/package.json"
      - "web-app/package-lock.json"

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Dependency review
        uses: actions/dependency-review-action@2031cfc080254a8a887f58cffee85186f0e49e48
